on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Helm Kubeval Action test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: helm kubeval
        uses: ./ # Uses an action in the root directory
        with:
          path: 'test/charts'
